--- !<MUTATOR>
contentType: "MUTATOR"
firstIndex: "2023-08-10 18:43"
game: "Unreal Tournament 2004"
name: "Bot Configuration"
author: "Nijel 'Morphias' Manthey"
description: "Change how bots behave in gameplay."
releaseDate: "2007-01"
attachments: []
originalFilename: "botconfig.zip"
hash: "9cc4bcbeeb97b0d34aaa38dfa16043f0e772be1d"
fileSize: 5756
files:
- name: "BotConfig.u"
  fileSize: 14107
  hash: "1312a2d8b0ca8df44ab32da80893aa9a41e8d215"
otherFiles: 3
dependencies: {}
downloads:
- url: "https://unreal-archive-files-s3.s3.us-west-002.backblazeb2.com/Unreal%20Tournament%202004/Mutators/B/9/c/c4bcbe/botconfig.zip"
  direct: true
  state: "OK"
links: {}
deleted: false
mutators:
- name: "Bot Configuration"
  description: "Change how bots behave in gameplay."
weapons: []
vehicles: []
hasConfigMenu: false
hasKeybinds: false
