--- !<MODEL>
contentType: "MODEL"
firstIndex: "2022-12-25 17:32"
variationOf: "d4e20d361b56147065d278579007958570546707"
game: "Unreal Tournament 2004"
name: "Trainer"
author: "Unknown"
description: "None"
releaseDate: "2009-01"
attachments:
- type: "IMAGE"
  name: "trainer_shot_9cf500bc_1.png"
  url: "https://f002.backblazeb2.com/file/unreal-archive-images/Unreal%20Tournament%202004/Models/T/9/c/f500bc/trainer_shot_9cf500bc_1.png"
originalFilename: "ut2k4-trainergirl-teamcolorupdatev.7z"
hash: "9cf500bc992931e173e28b25d509e63d4bc07e53"
fileSize: 7239630
files:
- name: "UT_TrainerRed.ukx"
  fileSize: 1251723
  hash: "9e3fbf0ea7b2964e14f7be63aa09fe25bdc66f0b"
- name: "UT_Trainertex_CTF4.utx"
  fileSize: 29836173
  hash: "23468c054ca13681b05b1a51dffdb3982baaa497"
- name: "UT_TrainerBlonde.ukx"
  fileSize: 1251724
  hash: "2b4116308b9b2a2ac8eb02d1a3ba90f23853fa64"
- name: "dUT_Trainer.upl"
  fileSize: 27439
  hash: "dd5296d6cfbfe8f8d48e78a74f808ed886f6dc81"
- name: "UT_Trainer08.ukx"
  fileSize: 1251707
  hash: "6a8cfa0ec8733daf1b8fbdfcde09eaf954e168e8"
otherFiles: 4
dependencies:
  UT_TrainerRed.ukx:
  - status: "OK"
    name: "UT_Trainertex_CTF4"
  UT_Trainer08.ukx:
  - status: "OK"
    name: "UT_Trainertex_CTF4"
  UT_TrainerBlonde.ukx:
  - status: "OK"
    name: "UT_Trainertex_CTF4"
downloads:
- url: "https://f002.backblazeb2.com/file/unreal-archive-files/Unreal%20Tournament%202004/Models/T/9/c/f500bc/ut2k4-trainergirl-teamcolorupdatev.7z"
  main: true
  repack: false
  state: "OK"
- url: "https://unreal-archive-files.eu-central-1.linodeobjects.com/Unreal%20Tournament%202004/Models/T/9/c/f500bc/ut2k4-trainergirl-teamcolorupdatev.7z"
  main: false
  repack: false
  state: "OK"
links: {}
deleted: false
models:
- "Trainer"
- "Marisol"
- "Chalia"
skins:
- "Trainer"
- "Amari"
- "Soledad"
- "Maritsa"
- "Celda"
- "Carmelita"
- "Marisol"
- "Chabelita"
- "Yeni"
- "Maite"
- "Delia"
- "Chalia"
- "Merche"
- "Conchita"
- "Tania"
- "Maribel"
- "PurpleTrainer"
- "Geneviève"
- "Nathalie"
- "Valérie"
- "Athéna"
- "Cassandre"
- "Carole"
- "Ingrid"
- "Aurore"
- "Yvonne"
- "Arlette"
- "Gwenaelle"
- "Manette"
- "Marianne"
- "Luan"
- "Adriane"
- "SkaarjHunter"
- "Vathen"
- "Keltna"
- "Aeltan"
- "Ventrax"
- "Methena"
- "Telan"
- "Charnat"
- "Osirix"
- "Feskel"
- "Miskai"
- "Tranthel"
- "Tergan"
- "Urhian"
- "Razel"
- "Solex"
- "FemaleStormTrooper"
- "Unit0097"
- "Unit0100"
- "Unit2301"
- "Unit0422"
- "Unit1023"
- "Unit0507"
- "Unit0780"
- "Unit0041"
- "Unit1152"
- "Unit1863"
- "Unit0567"
- "Unit0980"
- "Unit0771"
- "Unit0802"
- "Unit1383"
- "GhostTrainer"
- "GoldTrainer"
- "UTC-Trainer"
- "UTC-PurpleTrainer"
- "UTC-SkaarjHunter"
- "UTC-FemaleStormTrooper"
