--- !<MUTATOR>
contentType: "MUTATOR"
firstIndex: "2019-02-19 19:31"
game: "Unreal Tournament 2003"
name: "Custom Config - change settings for in-game play."
author: "Unknown"
description: ""
releaseDate: "2003-07"
attachments: []
originalFilename: "customconfig_v11.zip"
hash: "d981c36283fdac62309bcb358109b1e19765947c"
fileSize: 8190
files:
- name: "CustomConfig.u"
  fileSize: 16677
  hash: "8718eb0786c886d1ee88660e2558d3e40bd4db3d"
otherFiles: 4
dependencies: {}
downloads:
- url: "https://files.vohzd.com/unreal/unreal-tournament-2004/mutators/customconfig_v11.zip"
  direct: true
  state: "OK"
- url: "https://unreal-archive-files.eu-central-1.linodeobjects.com/Unreal%20Tournament%202004/Mutators/C/d/9/81c362/customconfig_v11.zip"
  direct: true
  state: "OK"
- url: "https://unrealarchiveusa.blob.core.windows.net/files/Unreal%20Tournament%202004/Mutators/C/d/9/81c362/customconfig_v11.zip"
  direct: true
  state: "OK"
- url: "https://unrealarchivesgp.blob.core.windows.net/files/Unreal%20Tournament%202004/Mutators/C/d/9/81c362/customconfig_v11.zip"
  direct: true
  state: "OK"
- url: "https://unreal-archive-files-s3.s3.us-west-002.backblazeb2.com/Unreal%20Tournament%202004/Mutators/C/d/9/81c362/customconfig_v11.zip"
  direct: true
  state: "OK"
links: {}
problemLinks: {}
deleted: false
mutators:
- name: "Custom Config - change settings for in-game play."
  description: ""
weapons: []
vehicles: []
hasConfigMenu: false
hasKeybinds: false
